name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: QuangTVTD/Jenkins@main
        with:
          path: 'json.json'
          contents:
            hello: 'world'
      - uses: actions/upload-artifact@v1
        with:
          name: json
          path: 'json.json'
