name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: QuangTVTD/Jenkins@master
        with:
          path: 'json.json'
          contents:
            hello: 'world'
      - uses: QuangTVTD/Jenkins@master
        with:
          path: 'yaml.yml'
          contents:
            - foo: 'bar'
              data:
                - 1
                - 2
      - uses: actions/upload-artifact@v1
        with:
          name: json
          path: 'json.json'
      - uses: actions/upload-artifact@v1
        with:
          name: yaml
          path: 'yaml.yml'
